// <auto-generated />
using System;
using Finance.Application.Infrastructure.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Finance.Application.Infrastructure.Storage.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20261005120921_ForgetLastAccount")]
    partial class ForgetLastAccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Finance.Application.Infrastructure.Storage.Rows.AccountRow", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("currency");

                    b.Property<string>("DeletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at_utc");

                    b.Property<bool>("ExcludedFromTotals")
                        .HasColumnType("INTEGER")
                        .HasColumnName("excluded_from_totals");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT")
                        .HasColumnName("icon");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_closed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateOnly>("OpenedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("opened_on");

                    b.Property<long>("OpeningBalance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("opening_balance");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("SyncedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("synced_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Key");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("ix_accounts_sort_order");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Finance.Application.Infrastructure.Storage.Rows.CategoryRow", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<bool?>("AcceptsAnyKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accepts_any_kind");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at_utc");

                    b.Property<bool>("ExcludeFromReports")
                        .HasColumnType("INTEGER")
                        .HasColumnName("exclude_from_reports");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("icon");

                    b.Property<string>("Kind")
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ParentKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_key");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("SyncedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("synced_at_utc");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Key");

                    b.HasIndex("ParentKey")
                        .HasDatabaseName("ix_categories_parent_key");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Finance.Application.Infrastructure.Storage.Rows.PlaceRow", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SyncedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("synced_at_utc");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Key");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_places_name");

                    b.ToTable("places", (string)null);
                });

            modelBuilder.Entity("Finance.Application.Infrastructure.Storage.Rows.SettingRow", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Name");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("Finance.Application.Infrastructure.Storage.Rows.TransactionRow", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<long>("Amount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("amount");

                    b.Property<string>("CategoryKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("category_key");

                    b.Property<string>("CreatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DeletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("ExternalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("external_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_on");

                    b.Property<string>("PlaceKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("place_key");

                    b.Property<string>("SourceAccountKey")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_account_key");

                    b.Property<string>("SyncedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("synced_at_utc");

                    b.Property<string>("TargetAccountKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("target_account_key");

                    b.Property<long?>("TargetAmount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_amount");

                    b.Property<string>("UpdatedAtUtc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Key");

                    b.HasIndex("PlaceKey")
                        .HasDatabaseName("ix_transactions_place_key")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.HasIndex("CategoryKey", "OccurredOn")
                        .HasDatabaseName("ix_transactions_category_occurred_on")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.HasIndex("OccurredOn", "CreatedAtUtc", "Key")
                        .IsDescending()
                        .HasDatabaseName("ix_transactions_feed")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.HasIndex("SourceAccountKey", "OccurredOn", "CreatedAtUtc", "Key")
                        .IsDescending(false, true, true, true)
                        .HasDatabaseName("ix_transactions_source_feed")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.HasIndex("TargetAccountKey", "OccurredOn", "CreatedAtUtc", "Key")
                        .IsDescending(false, true, true, true)
                        .HasDatabaseName("ix_transactions_target_feed")
                        .HasFilter("deleted_at_utc IS NULL");

                    b.ToTable("transactions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
